export let role = "admin"

const today = new Date(); // Current date
const year = today.getFullYear();
const month = today.getMonth(); // Month starts from 0 in JavaScript Date
const day = today.getDate();

export const calendarEvents = [
  {
    title: "Math",
    allDay: false,
    start: new Date(year, month, day, 8, 0),
    end: new Date(year, month, day, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(year, month, 26, 9, 0),
    end: new Date(year, month, 26, 9, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(year, month, 24, 10, 0),
    end: new Date(year, month, 24, 10, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(year, month, day, 11, 0),
    end: new Date(year, month, day, 11, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(year, month, day, 12, 0),
    end: new Date(year, month, day, 12, 45),
  },
  {
    title: "Geography",
    allDay: false,
    start: new Date(year, month, day, 13, 0),
    end: new Date(year, month, day, 13, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(year, month, day, 14, 0),
    end: new Date(year, month, day, 14, 45),
  },
  {
    title: "Computer Science",
    allDay: false,
    start: new Date(year, month, day, 15, 0),
    end: new Date(year, month, day, 15, 45),
  },
//   {
//     title: "Physical Education",
//     allDay: false,
//     start: new Date(year, month, day, 13, 30),
//     end: new Date(year, month, day, 13, 45),
//   },
//   {
//     title: "Art",
//     allDay: false,
//     start: new Date(year, month, day, 15, 25),
//     end: new Date(year, month, day, 15, 45),
//   }
];

export const teachers = [
  {
      id: 960,
      name: 'Stephanie Brown',
      email: 'wilsoncraig@ramirez.net',
      phone: '020.032.2883x66836',
      photo: 'https://www.lorempixel.com/200/200',
      subjects: ['English', 'Physical Education', 'Science'],
      classes: ['Class 6', 'Class 8', 'Class 5', 'Class 9'],
      address: '80025 Smith Centers Apt. 642, North Nicoleport, NC 36937',
  },
  {
      id: 109,
      name: 'Donald Lewis',
      email: 'prattrobert@yahoo.com',
      phone: '6583233137',
      photo: 'https://dummyimage.com/200x200',
      subjects: ['Music'],
      classes: ['Class 9', 'Class 12'],
      address: '51319 Francis Tunnel Suite 396, Port Robert, OH 49938',
  },
  {
      id: 318,
      name: 'Laura Dillon',
      email: null,
      phone: '(341)563-2915',
      photo: 'https://placeimg.com/200/200/any',
      subjects: ['Math', 'History', 'Physical Education'],
      classes: ['Class 2', 'Class 1'],
      address: '8609 Massey Center, Stevenhaven, MO 18687',
  },
  {
      id: 4,
      name: 'Danielle Jones',
      email: 'nhoward@johnson.biz',
      phone: '046.334.3604',
      photo: 'https://www.lorempixel.com/200/200',
      subjects: ['Science'],
      classes: ['Class 9', 'Class 4'],
      address: '382 Obrien Locks, Joshuashire, NV 08097',
  },
  {
      id: 958,
      name: 'Allison Hancock',
      email: null,
      phone: '(473)570-7812x6267',
      photo: 'https://www.lorempixel.com/200/200',
      subjects: ['English', 'Physical Education'],
      classes: ['Class 4'],
      address: '45011 Brown Trail Apt. 376, South Stevenborough, WA 48320',
  },
  {
      id: 181,
      name: 'Monica Brown',
      email: null,
      phone: '(940)517-9131',
      photo: 'https://www.lorempixel.com/200/200',
      subjects: ['Science', 'Music', 'History'],
      classes: ['Class 9', 'Class 7'],
      address: '0107 Eaton Key Apt. 309, North Samuel, IN 77643',
  },
  {
      id: 684,
      name: 'Kevin Jones',
      email: null,
      phone: '001-734-462-8058x94666',
      photo: 'https://placeimg.com/200/200/any',
      subjects: ['Geography', 'Math', 'English'],
      classes: ['Class 10', 'Class 12', 'Class 2', 'Class 7'],
      address: '94964 Mclean Passage Suite 881, Lake Alan, OR 13276',
  },
  {
      id: 312,
      name: 'Patrick Gonzalez',
      email: 'waustin@hotmail.com',
      phone: '823-793-8074x1885',
      photo: 'https://dummyimage.com/200x200',
      subjects: ['Physical Education', 'Art', 'Science'],
      classes: ['Class 4', 'Class 12', 'Class 10'],
      address: '173 Riley Pines Apt. 603, Port Michaelchester, PA 62271',
  },
  {
      id: 499,
      name: 'Alexander Thornton',
      email: 'nsalazar@thompson-king.info',
      phone: '024-877-6780x858',
      photo: 'https://www.lorempixel.com/200/200',
      subjects: ['Science', 'English', 'Music'],
      classes: ['Class 6', 'Class 11'],
      address: '33445 Wilson Summit Suite 780, Waynemouth, ME 42948',
  },
  {
      id: 100,
      name: 'Breanna Owens',
      email: 'adamskatie@yahoo.com',
      phone: '001-529-603-5312x34598',
      photo: 'https://placekitten.com/200/200',
      subjects: ['Math', 'Music'],
      classes: ['Class 4', 'Class 5', 'Class 6', 'Class 12'],
      address: '1242 Lisa Plain Suite 522, West Stevenshire, RI 98280',
  }
];

export const students = [
  { id: 1, studentId: 'S001', name: 'John Doe', email: 'johndoe@example.com', phone: '123-456-7890', photo: 'john_photo.jpg', grade: 'A', class: 'Math', address: '123 Maple St.' },
  { id: 2, studentId: 'S002', name: 'Jane Smith', email: 'janesmith@example.com', phone: '234-567-8901', photo: 'jane_photo.jpg', grade: 'B', class: 'Science', address: '456 Oak St.' },
  { id: 3, studentId: 'S003', name: 'Michael Johnson', email: 'michaelj@example.com', phone: '345-678-9012', photo: 'michael_photo.jpg', grade: 'C', class: 'History', address: '789 Pine St.' },
  { id: 4, studentId: 'S004', name: 'Emily Brown', phone: '456-789-0123', photo: 'emily_photo.jpg', grade: 'B', class: 'English', address: '321 Cedar Ave.' },
  { id: 5, studentId: 'S005', name: 'David Wilson', email: 'davidwilson@example.com', phone: '567-890-1234', photo: 'david_photo.jpg', grade: 'A', class: 'Chemistry', address: '654 Birch Rd.' },
  { id: 6, studentId: 'S006', name: 'Sarah Davis', email: 'sarahd@example.com', phone: '678-901-2345', photo: 'sarah_photo.jpg', grade: 'A', class: 'Math', address: '987 Elm St.' },
  { id: 7, studentId: 'S007', name: 'Daniel Miller', email: 'danielm@example.com', phone: '789-012-3456', photo: 'daniel_photo.jpg', grade: 'C', class: 'Physics', address: '741 Spruce Dr.' },
  { id: 8, studentId: 'S008', name: 'Jessica Lee', phone: '890-123-4567', photo: 'jessica_photo.jpg', grade: 'B', class: 'Geography', address: '852 Willow Ln.' },
  { id: 9, studentId: 'S009', name: 'William Taylor', email: 'willt@example.com', phone: '901-234-5678', photo: 'william_photo.jpg', grade: 'C', class: 'History', address: '963 Fir St.' },
  { id: 10, studentId: 'S010', name: 'Olivia Anderson', email: 'oliviaa@example.com', phone: '012-345-6789', photo: 'olivia_photo.jpg', grade: 'A', class: 'Math', address: '123 Ash Blvd.' },
  { id: 11, studentId: 'S011', name: 'James Moore', phone: '123-456-7890', photo: 'james_photo.jpg', grade: 'B', class: 'Science', address: '234 Poplar St.' },
  { id: 12, studentId: 'S012', name: 'Sophia Martin', email: 'sophiam@example.com', phone: '234-567-8901', photo: 'sophia_photo.jpg', grade: 'A', class: 'English', address: '345 Redwood Ave.' },
  { id: 13, studentId: 'S013', name: 'Benjamin Jackson', phone: '345-678-9012', photo: 'benjamin_photo.jpg', grade: 'C', class: 'Math', address: '456 Walnut Dr.' },
  { id: 14, studentId: 'S014', name: 'Ava White', email: 'avawhite@example.com', phone: '456-789-0123', photo: 'ava_photo.jpg', grade: 'B', class: 'Biology', address: '567 Pine Ave.' },
  { id: 15, studentId: 'S015', name: 'Alexander Harris', phone: '567-890-1234', photo: 'alexander_photo.jpg', grade: 'A', class: 'Chemistry', address: '678 Chestnut Blvd.' },
  { id: 16, studentId: 'S016', name: 'Mia Thompson', email: 'miat@example.com', phone: '678-901-2345', photo: 'mia_photo.jpg', grade: 'C', class: 'History', address: '789 Maple St.' },
  { id: 17, studentId: 'S017', name: 'Elijah Robinson', phone: '789-012-3456', photo: 'elijah_photo.jpg', grade: 'B', class: 'Physics', address: '891 Oak St.' },
  { id: 18, studentId: 'S018', name: 'Isabella Martinez', email: 'isabellam@example.com', phone: '890-123-4567', photo: 'isabella_photo.jpg', grade: 'A', class: 'Geography', address: '123 Birch Ave.' },
  { id: 19, studentId: 'S019', name: 'Lucas Clark', email: 'lucasc@example.com', phone: '901-234-5678', photo: 'lucas_photo.jpg', grade: 'C', class: 'Math', address: '234 Elm Rd.' },
  { id: 20, studentId: 'S020', name: 'Charlotte Lewis', phone: '012-345-6789', photo: 'charlotte_photo.jpg', grade: 'B', class: 'English', address: '345 Cedar St.' }
];

export const parents = [
  { id: 1, name: 'Mark Doe', email: 'markdoe@example.com', phone: '123-456-7890', students: ['S001', 'S002'], address: '123 Maple St.' },
  { id: 2, name: 'Laura Smith', email: 'laurasmith@example.com', phone: '234-567-8901', students: ['S003'], address: '456 Oak St.' },
  { id: 3, name: 'Robert Johnson', phone: '345-678-9012', students: ['S004', 'S005'], address: '789 Pine St.' },
  { id: 4, name: 'Emily Brown', email: 'emilyb@example.com', phone: '456-789-0123', students: ['S006'], address: '321 Cedar Ave.' },
  { id: 5, name: 'Michael Wilson', phone: '567-890-1234', students: ['S007', 'S008'], address: '654 Birch Rd.' },
  { id: 6, name: 'Sarah Davis', email: 'sarahdavis@example.com', phone: '678-901-2345', students: ['S009'], address: '987 Elm St.' },
  { id: 7, name: 'Daniel Miller', email: 'danielmiller@example.com', phone: '789-012-3456', students: ['S010', 'S011'], address: '741 Spruce Dr.' },
  { id: 8, name: 'Jessica Lee', phone: '890-123-4567', students: ['S012'], address: '852 Willow Ln.' },
  { id: 9, name: 'William Taylor', email: 'willtaylor@example.com', phone: '901-234-5678', students: ['S013', 'S014'], address: '963 Fir St.' },
  { id: 10, name: 'Olivia Anderson', phone: '012-345-6789', students: ['S015'], address: '123 Ash Blvd.' },
  { id: 11, name: 'James Moore', email: 'jamesmoore@example.com', phone: '123-456-7890', students: ['S016', 'S017'], address: '234 Poplar St.' },
  { id: 12, name: 'Sophia Martin', phone: '234-567-8901', students: ['S018'], address: '345 Redwood Ave.' },
  { id: 13, name: 'Benjamin Jackson', email: 'benjaminj@example.com', phone: '345-678-9012', students: ['S019', 'S020'], address: '456 Walnut Dr.' },
  { id: 14, name: 'Ava White', phone: '456-789-0123', students: ['S001', 'S002'], address: '567 Pine Ave.' },
  { id: 15, name: 'Alexander Harris', email: 'alexh@example.com', phone: '567-890-1234', students: ['S003'], address: '678 Chestnut Blvd.' },
  { id: 16, name: 'Mia Thompson', phone: '678-901-2345', students: ['S004'], address: '789 Maple St.' },
  { id: 17, name: 'Elijah Robinson', email: 'elijahr@example.com', phone: '789-012-3456', students: ['S005', 'S006'], address: '891 Oak St.' },
  { id: 18, name: 'Isabella Martinez', phone: '890-123-4567', students: ['S007'], address: '123 Birch Ave.' },
  { id: 19, name: 'Lucas Clark', email: 'lucasclark@example.com', phone: '901-234-5678', students: ['S008', 'S009'], address: '234 Elm Rd.' },
  { id: 20, name: 'Charlotte Lewis', phone: '012-345-6789', students: ['S010'], address: '345 Cedar St.' }
];

export const subjects = [
  {
    id: 1,
    name: "Mathematics",
    teachers: ["John Doe", "Jane Smith", "Alice Johnson"],
  },
  {
    id: 2,
    name: "English",
    teachers: ["Michael Brown", "Emma Davis"],
  },
  {
    id: 3,
    name: "Physics",
    teachers: ["Chris Evans", "Robert Green", "Sophia Miller"],
  },
  {
    id: 4,
    name: "Chemistry",
    teachers: ["Nancy White", "David Thompson"],
  },
  {
    id: 5,
    name: "Biology",
    teachers: ["Laura Lewis", "Henry Martin", "Jessica Clark"],
  },
  {
    id: 6,
    name: "History",
    teachers: ["Ethan Turner", "Olivia Martinez"],
  },
  {
    id: 7,
    name: "Geography",
    teachers: ["Samuel Harris", "Liam Moore", "Charlotte Hall"],
  },
  {
    id: 8,
    name: "Computer Science",
    teachers: ["Daniel Scott", "Ella King"],
  },
  {
    id: 9,
    name: "Art",
    teachers: ["Grace Adams", "Ava Mitchell"],
  },
  {
    id: 10,
    name: "Physical Education",
    teachers: ["James Taylor", "Madison Lopez"],
  },
];

export const classes = [
  {
    id: 1,
    name: "Class A",
    capacity: 30,
    grade: 5,
    supervisor: "Alice Johnson",
  },
  {
    id: 2,
    name: "Class B",
    capacity: 28,
    grade: 6,
    supervisor: "John Doe",
  },
  {
    id: 3,
    name: "Class C",
    capacity: 25,
    grade: 4,
    supervisor: "Emma Davis",
  },
  {
    id: 4,
    name: "Class D",
    capacity: 32,
    grade: 3,
    supervisor: "Michael Brown",
  },
  {
    id: 5,
    name: "Class E",
    capacity: 27,
    grade: 5,
    supervisor: "Nancy White",
  },
  {
    id: 6,
    name: "Class F",
    capacity: 29,
    grade: 7,
    supervisor: "Sophia Miller",
  },
  {
    id: 7,
    name: "Class G",
    capacity: 24,
    grade: 8,
    supervisor: "David Thompson",
  },
  {
    id: 8,
    name: "Class H",
    capacity: 30,
    grade: 6,
    supervisor: "Robert Green",
  },
  {
    id: 9,
    name: "Class I",
    capacity: 26,
    grade: 7,
    supervisor: "Chris Evans",
  },
  {
    id: 10,
    name: "Class J",
    capacity: 22,
    grade: 3,
    supervisor: "Jessica Clark",
  },
];

export const lessons = [
  {
    id: 1,
    subject: "Mathematics - Algebra",
    class: "Class A",
    teacher: "Alice Johnson",
  },
  {
    id: 2,
    subject: "Science - Biology",
    class: "Class B",
    teacher: "John Doe",
  },
  {
    id: 3,
    subject: "History - World War II",
    class: "Class C",
    teacher: "Emma Davis",
  },
  {
    id: 4,
    subject: "English - Literature",
    class: "Class D",
    teacher: "Michael Brown",
  },
  {
    id: 5,
    subject: "Geography - Physical Geography",
    class: "Class E",
    teacher: "Nancy White",
  },
  {
    id: 6,
    subject: "Mathematics - Geometry",
    class: "Class F",
    teacher: "Sophia Miller",
  },
  {
    id: 7,
    subject: "Chemistry - Organic Chemistry",
    class: "Class G",
    teacher: "David Thompson",
  },
  {
    id: 8,
    subject: "Physics - Mechanics",
    class: "Class H",
    teacher: "Robert Green",
  },
  {
    id: 9,
    subject: "Computer Science - Programming",
    class: "Class I",
    teacher: "Chris Evans",
  },
  {
    id: 10,
    subject: "Physical Education - Athletics",
    class: "Class J",
    teacher: "Jessica Clark",
  },
];

export const exams = [
  {
    id: 1,
    subject: "Mathematics",
    class: "Class A",
    teacher: "Alice Johnson",
    date: "2024-11-15",
  },
  {
    id: 2,
    subject: "Biology",
    class: "Class B",
    teacher: "John Doe",
    date: "2024-11-18",
  },
  {
    id: 3,
    subject: "History",
    class: "Class C",
    teacher: "Emma Davis",
    date: "2024-11-20",
  },
  {
    id: 4,
    subject: "Literature",
    class: "Class D",
    teacher: "Michael Brown",
    date: "2024-11-22",
  },
  {
    id: 5,
    subject: "Geography",
    class: "Class E",
    teacher: "Nancy White",
    date: "2024-11-25",
  },
  {
    id: 6,
    subject: "Physics",
    class: "Class F",
    teacher: "Robert Green",
    date: "2024-11-27",
  },
  {
    id: 7,
    subject: "Chemistry",
    class: "Class G",
    teacher: "David Thompson",
    date: "2024-11-29",
  },
  {
    id: 8,
    subject: "Computer Science",
    class: "Class H",
    teacher: "Chris Evans",
    date: "2024-12-01",
  },
  {
    id: 9,
    subject: "Physical Education",
    class: "Class I",
    teacher: "Jessica Clark",
    date: "2024-12-03",
  },
  {
    id: 10,
    subject: "Economics",
    class: "Class J",
    teacher: "James Wilson",
    date: "2024-12-05",
  },
];

export const assignments = [
  {
    id: 1,
    subject: "Mathematics",
    class: "Class A",
    teacher: "Alice Johnson",
    dueDate: "2024-11-15",
  },
  {
    id: 2,
    subject: "Biology",
    class: "Class B",
    teacher: "John Doe",
    dueDate: "2024-11-18",
  },
  {
    id: 3,
    subject: "History",
    class: "Class C",
    teacher: "Emma Davis",
    dueDate: "2024-11-20",
  },
  {
    id: 4,
    subject: "Literature",
    class: "Class D",
    teacher: "Michael Brown",
    dueDate: "2024-11-22",
  },
  {
    id: 5,
    subject: "Geography",
    class: "Class E",
    teacher: "Nancy White",
    dueDate: "2024-11-25",
  },
  {
    id: 6,
    subject: "Physics",
    class: "Class F",
    teacher: "Robert Green",
    dueDate: "2024-11-27",
  },
  {
    id: 7,
    subject: "Chemistry",
    class: "Class G",
    teacher: "David Thompson",
    dueDate: "2024-11-29",
  },
  {
    id: 8,
    subject: "Computer Science",
    class: "Class H",
    teacher: "Chris Evans",
    dueDate: "2024-12-01",
  },
  {
    id: 9,
    subject: "Physical Education",
    class: "Class I",
    teacher: "Jessica Clark",
    dueDate: "2024-12-03",
  },
  {
    id: 10,
    subject: "Economics",
    class: "Class J",
    teacher: "James Wilson",
    dueDate: "2024-12-05",
  },
];

export const results = [
  {
    id: 1,
    subject: "Mathematics",
    class: "SS1A",
    teacher: "Mr. Okoro",
    student: "Adebola Johnson",
    type: "exam",
    date: "2024-06-10",
    score: 85, // High scores are often seen as excellent performance
  },
  {
    id: 2,
    subject: "English Language",
    class: "JS2B",
    teacher: "Mrs. Akinwale",
    student: "Chinwe Eze",
    type: "assignment",
    date: "2024-06-11",
    score: 65, // Mid-range scores for assignment
  },
  {
    id: 3,
    subject: "Physics",
    class: "SS2C",
    teacher: "Dr. Uche",
    student: "Emeka Nwankwo",
    type: "exam",
    date: "2024-06-15",
    score: 92, // Excellent score
  },
  {
    id: 4,
    subject: "Chemistry",
    class: "SS3D",
    teacher: "Mr. Bello",
    student: "Hassan Ibrahim",
    type: "assignment",
    date: "2024-06-16",
    score: 74, // Good score
  },
  {
    id: 5,
    subject: "Biology",
    class: "SS1A",
    teacher: "Miss Adebayo",
    student: "Bolu Adebayo",
    type: "exam",
    date: "2024-06-20",
    score: 58, // Lower score, indicating more room for improvement
  },
  {
    id: 6,
    subject: "Economics",
    class: "JS3B",
    teacher: "Mrs. Ojo",
    student: "Tunde Oladipo",
    type: "assignment",
    date: "2024-06-22",
    score: 81, // Strong performance in assignment
  },
  {
    id: 7,
    subject: "Literature in English",
    class: "SS2A",
    teacher: "Mr. Adebisi",
    student: "Nkechi Okafor",
    type: "exam",
    date: "2024-06-25",
    score: 69, // Satisfactory score
  },
  {
    id: 8,
    subject: "Government",
    class: "SS3C",
    teacher: "Mr. Peters",
    student: "Abubakar Musa",
    type: "exam",
    date: "2024-06-27",
    score: 73, // Slightly above average
  },
  {
    id: 9,
    subject: "Agricultural Science",
    class: "JS2A",
    teacher: "Mrs. Williams",
    student: "Efe Adams",
    type: "assignment",
    date: "2024-06-30",
    score: 59, // Borderline pass
  },
  {
    id: 10,
    subject: "Civic Education",
    class: "JS1C",
    teacher: "Mr. James",
    student: "Yusuf Bello",
    type: "exam",
    date: "2024-07-02",
    score: 88, // High score
  },
];

export const events = [
  {
    id: 1,
    title: "Mathematics Seminar",
    class: "SS1",
    date: "2024-10-05",
    startTime: "09:00 AM",
    endTime: "11:00 AM",
  },
  {
    id: 2,
    title: "Science Quiz Competition",
    class: "JSS3",
    date: "2024-10-10",
    startTime: "10:00 AM",
    endTime: "12:00 PM",
  },
  {
    id: 3,
    title: "Sports Day",
    class: "All",
    date: "2024-10-15",
    startTime: "08:00 AM",
    endTime: "02:00 PM",
  },
  {
    id: 4,
    title: "Cultural Day",
    class: "SS2",
    date: "2024-10-20",
    startTime: "11:00 AM",
    endTime: "01:00 PM",
  },
  {
    id: 5,
    title: "Parent-Teacher Meeting",
    class: "SS3",
    date: "2024-10-25",
    startTime: "01:00 PM",
    endTime: "03:00 PM",
  },
  {
    id: 6,
    title: "Chemistry Practical",
    class: "SS1",
    date: "2024-10-30",
    startTime: "09:30 AM",
    endTime: "11:00 AM",
  },
  {
    id: 7,
    title: "Biology Exhibition",
    class: "JSS2",
    date: "2024-11-02",
    startTime: "12:00 PM",
    endTime: "02:00 PM",
  },
  {
    id: 8,
    title: "Annual Speech & Prize Giving Day",
    class: "All",
    date: "2024-11-07",
    startTime: "10:00 AM",
    endTime: "01:00 PM",
  },
  {
    id: 9,
    title: "English Language Debate",
    class: "SS1",
    date: "2024-11-12",
    startTime: "11:00 AM",
    endTime: "01:00 PM",
  },
  {
    id: 10,
    title: "Inter-House Sports Competition",
    class: "All",
    date: "2024-11-20",
    startTime: "08:30 AM",
    endTime: "04:00 PM",
  },
];

export const announcements = [
  {
    id: 1,
    title: "Mid-Term Break Announcement",
    class: "All",
    date: "2024-10-05",
  },
  {
    id: 2,
    title: "New School Uniform Guidelines",
    class: "All",
    date: "2024-10-10",
  },
  {
    id: 3,
    title: "SS1 Mathematics Tutorial",
    class: "SS1",
    date: "2024-10-12",
  },
  {
    id: 4,
    title: "JSS2 Parent-Teacher Conference",
    class: "JSS2",
    date: "2024-10-15",
  },
  {
    id: 5,
    title: "Inter-House Sports Registration",
    class: "All",
    date: "2024-10-18",
  },
  {
    id: 6,
    title: "SS3 WAEC Preparation Classes",
    class: "SS3",
    date: "2024-10-20",
  },
  {
    id: 7,
    title: "JSS1 Science Practical Session",
    class: "JSS1",
    date: "2024-10-25",
  },
  {
    id: 8,
    title: "School Assembly Time Change",
    class: "All",
    date: "2024-10-27",
  },
  {
    id: 9,
    title: "School Sanitation Day",
    class: "All",
    date: "2024-11-02",
  },
  {
    id: 10,
    title: "SS2 Literature Debate",
    class: "SS2",
    date: "2024-11-05",
  },
];
