export { default as Home } from "./home"
export { default as About } from "./about"
export { default as AdminDashboard } from "./dashboards/AdminDashboard"
export { default as StudentDashboard } from "./dashboards/StudentDashboard"
export { default as ParentDashboard } from "./dashboards/ParentDashboard"
export { default as TeacherDashboard } from "./dashboards/TeacherDashboard"
